version: "3.8"

services:
  frontend:
    container_name: relotfrontend
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3000
    ports:
      - "3003:3003"
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
