version: "3.8"

services:
  frontend:
    container_name: relotfrontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    env_file:
      - .env
    restart: unless-stopped
