version: "3.8"

services:
  frontend:
    container_name: relotfrontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    volumes:
      - ./.env.production:/app/.env.production:ro
    restart: unless-stopped
