version: "3.8"

services:
  frontend:
    container_name: relotfrontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        FRONTEND_ENV: ${FRONTEND_ENV}
    environment:
      - NODE_ENV=production
    ports:
      - "3003:3003"
    restart: unless-stopped
