name: VPS Deploy Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploytovps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Add VPS to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Copy code to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "/root/frontend"

      - name: Rebuild and start containers on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root/frontend
            echo "${{ secrets.FRONTEND_ENV }}" > .env.production
            export FRONTEND_ENV="$(cat .env.production | sed ':a;N;$!ba;s/\n/\\n/g')"
            docker compose -f docker-compose.prod.yml down --rmi all --remove-orphans || true
            FRONTEND_ENV="$FRONTEND_ENV" docker compose -f docker-compose.prod.yml build --no-cache
            docker compose -f docker-compose.prod.yml up -d
