# .github/workflows/hello-world.yml

name: VPS Deploy Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
      

jobs:
  deploytovps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      
      - name: Add VPS to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Copy code to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "/root/frontend"
      - name: Set .env file on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
            host: ${{ secrets.SERVER_IP }}
            username: root
            key: ${{ secrets.SSH_KEY }}
            script: |
                cd /root/frontend
                echo "${{ secrets.FRONTEND_ENV }}" > .env

      - name: Rebuild and start containers on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root/frontend
            docker compose -f docker-compose.prod.yml down || true
            docker compose -f docker-compose.prod.yml up -d --build